name: algoriza_phase1_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  uuid: ^3.0.6
  sqflite: ^2.0.3+1
  hexcolor: ^2.0.7
  date_picker_timeline: ^1.2.3
  intl: ^0.17.0
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  ansicolor: ^2.0.1
  workmanager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/todo_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/